// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc0VLL8hV5SUl6sS6DDYLbAtxMrMMtWfs',
    appId: '1:748501289504:web:3d59c38dec9cc8bfa30a45',
    messagingSenderId: '748501289504',
    projectId: 'ticketing-app-4f2fe',
    authDomain: 'ticketing-app-4f2fe.firebaseapp.com',
    storageBucket: 'ticketing-app-4f2fe.firebasestorage.app',
    measurementId: 'G-NHJWH865V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUDf42XxMBbzvFPy5hafe6dng3JA9wvZI',
    appId: '1:748501289504:android:16c1e048590ac651a30a45',
    messagingSenderId: '748501289504',
    projectId: 'ticketing-app-4f2fe',
    storageBucket: 'ticketing-app-4f2fe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc0VLL8hV5SUl6sS6DDYLbAtxMrMMtWfs',
    appId: '1:748501289504:web:9a649d6b009039b5a30a45',
    messagingSenderId: '748501289504',
    projectId: 'ticketing-app-4f2fe',
    authDomain: 'ticketing-app-4f2fe.firebaseapp.com',
    storageBucket: 'ticketing-app-4f2fe.firebasestorage.app',
    measurementId: 'G-7LGY1WTWYT',
  );
}
